Sprint 2
IFabrichnov/middle.messenger.praktikum.yandex pull request #2
Opened 2024-10-29 18:51 UTC by IFabrichnov

2024-10-29 21:07 UTC, aromanovnik requested changes
Добрый день, Иван!

Работа выполнена очень хорошо: в проекте используются `enum`, добавлена валидация, учтена буква **Ё**, добавлены `ESLint` и `Stylelint`, а также применяется компонентный подход.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

**Что нужно исправить**:
* При запуске команды npm run lint обнаружена 1 проблема, которую необходимо решить.
* По заданию должен быть инпут для ввода сообщения, и на нем должна быть валидация. В данный момент валидация (`validatorMessage`) уже реализована, но сам инпут отсутствует.
* Нужно добавить строгую типизацию для Block и props. Сейчас использование `class Block<P extends Record<string, any> = any>` позволяет игнорировать строгую типизацию.

**Что можно улучшить**:
* У класса Block используется дженерик тип, правильнее будет при расширении класса передавать ему тип, например `Block<IProps>`. 
* В проекте **14** `any`, было бы супер уменьшить их количество, например, прописав конкретные типы, использовать дженерики или, в крайнем случае, заменить на unknown. 
* Использовать `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}` при типе params: `Record<string, any>` не стоит, так как значения могут быть не строками (объекты, массивы и т.д.), что приведет к ошибкам.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-10-29 21:07 UTC, aromanovnik commented on package.json
> +    "lint": "eslint . && stylelint \"**/*.pcss\"",
**Надо исправить**: При запуске команды `npm run lint` обнаружена 1 проблема, которую необходимо решить для соблюдения стандартов кодирования и улучшения качества кода.

<img width="550" alt="Снимок экрана 2024-10-29 в 22 51 17" src="https://github.com/user-attachments/assets/b7962c11-0737-4543-8635-9e0844d827c3">

2024-10-29 21:07 UTC, aromanovnik commented on src/utils/Block.ts
> +class Block<P extends Record<string, any> = any> {
**Надо исправить**: Нужно добавить строгую типизацию для Block и props. Сейчас использование `class Block<P extends Record<string, any> = any>` позволяет игнорировать строгую типизацию, что приводит к отсутствию типизации для всех свойств `props` во всех компонентах.

Пример в playground: https://www.typescriptlang.org/play/?&\=#code/MYGwhgzhAEBCIHtgGsA8AFATggDjApgB4Au+AdgCYwBK+wCmFqExmAlmQOYA00YZAT2gAfaAgBGAKzrEAfNAC8fQfIDeAKGjQc2PAC5oWXDCWqAvnxhG8AbnVn160JBgBBaEVKUY8JMmgaWvRkLJgArsDEDAAUAJQBmlrQEGE4+JhxdknQwRAIIPgAdIic0cQAFmwQhTrGsVlJAPSN2a1t0AB6APyJDg5AA

2024-10-29 21:07 UTC, aromanovnik commented on src/components/Button/Button.ts
> +export default class Button extends Block {
**Можно лучше**: У класса `Block` используется дженерик тип, правильнее будет при расширении класса передавать ему тип, например `Block<IProps>`. Это улучшит статическую типизацию и позволит избежать ошибок при работе с пропсами, так как TypeScript будет проверять соответствие типов на уровне компиляции, что делает код более безопасным и поддерживаемым.

2024-10-29 21:07 UTC, aromanovnik commented on src/utils/validators.ts
> +  return /^[A-ZА-ЯЁ][a-zа-яё-]*$/.test(el);
**Отлично!**: Учтена буква `Ё`, что важно, ведь в Юникоде она находится отдельно от диапазона `А-Я`. Это улучшает корректность обработки текстов на русском языке, обеспечивая точное сопоставление символов.

2024-10-29 21:07 UTC, aromanovnik commented on src/pages/login/LoginPage.ts
> +          const values = Object.fromEntries(formData as any);
**Можно лучше**: В проекте **14** `any`, было бы супер уменьшить их количество, например, прописав конкретные типы, использовать дженерики или, в крайнем случае, заменить на `unknown`. Это улучшит типизацию и сделает код более предсказуемым и безопасным.

2024-10-29 21:07 UTC, aromanovnik commented on src/pages/chat/chat.hbs
> +    <p class="empty-message">Выберите чат чтобы отправить сообщение</p>
**Надо исправить**: По заданию должен быть инпут для ввода сообщения, и на нем должна быть валидация. В данный момент валидация (`validatorMessage`) уже реализована, но сам инпут отсутствует. Нужно добавить инпут для ввода сообщения и применить к нему существующую валидацию.

2024-10-29 21:07 UTC, aromanovnik commented on src/utils/HTTPTransport.ts
> +enum RequestMethods {
**Отлично!**: Здорово, что в проекте используются enum.

2024-10-29 21:07 UTC, aromanovnik commented on src/utils/HTTPTransport.ts
> +  private static buildQueryString(params: Record<string, any>) {
Можно лучше: Использовать `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}` при типе `params: Record<string, any>` не стоит, так как значения могут быть не строками (объекты, массивы и т.д.), что приведет к ошибкам. Лучше ограничить тип как `Record<string, string>` или проверять тип данных и корректно преобразовывать — массивы через `.join(',')`, объекты через `JSON.stringify`.

2024-10-31 17:31 UTC, IFabrichnov commented
Добрый вечер! Поправил замечания из секции:

> **Что нужно исправить:**
>
> * При запуске команды npm run lint обнаружена 1 проблема, которую необходимо решить.
> * По заданию должен быть инпут для ввода сообщения, и на нем должна быть валидация. В данный момент валидация >>(validatorMessage) уже реализована, но сам инпут отсутствует.
> * Нужно добавить строгую типизацию для Block и props. Сейчас использование class Block<P extends Record<string, any> = >any> позволяет игнорировать строгую типизацию.

Секцию **Что можно улучшить**  поправлю до следующего спринта.

2024-10-31 19:45 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-11-25 15:27 UTC, merged