Sprint 3
IFabrichnov/middle.messenger.praktikum.yandex pull request #3
Opened 2024-11-22 13:52 UTC by IFabrichnov

2024-11-22 19:11 UTC, aromanovnik commented on package.json
> +  "scripts": {
**Можно лучше**: `npm audit` находит 3 уязвимости, которые лучше устранить. Это не только повысит безопасность приложения, но и улучшит его доверие среди пользователей и команд разработки. Исправить эти уязвимости можно автоматически с помощью команды `npm audit fix`. Если команда не устраняет все проблемы, то стоит проверить оставшиеся вручную, изучив документацию о найденных уязвимостях.

2024-11-22 20:32 UTC, aromanovnik requested changes
Добрый день, Иван!

Работа выполнена **очень хорошо**: код хорошо типизирован, используются `enum`, навигация работает корректно, чаты создаются, сообщения отправляются и отображаются без ошибок, авторизация и регистрация функционируют правильно. Код выглядит чисто и аккуратно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* Запрос на изменение пароля должен содержать только два поля: `newPassword` и `oldPassword`. Передача других данных, таких как имя или электронная почта, не имеет смысла и создает лишнюю нагрузку на сервер. Аналогично, при запросе на изменение данных пользователя, например имени или email, пароли передавать не нужно.
* Обновление информации пользователя и смена пароля должны быть реализованы в виде отдельных форм, так как эти действия логически не связаны. Например, если пользователь хочет изменить только имя в чате, не следует требовать изменения пароля. 

Что можно улучшить:
* Хорошей практикой является слияние пул реквестов с main после каждого спринта, чтобы каждый пул реквест содержал только изменения, относящиеся к текущему спринту. Это помогает поддерживать чистоту истории коммитов, упрощает процесс ревью и предотвращает появление смешанных изменений из разных этапов разработки.
* `npm audit` находит 3 уязвимости, которые лучше устранить.
* В проекте повторяется один и тот же код в нескольких местах. Лучше вынести его в отдельную функцию, чтобы соблюсти принцип DRY (Don’t Repeat Yourself). 
* После отправки сообщения текстовое поле ввода (input) должно очищаться. Это улучшит пользовательский опыт, так как пользователю не придется вручную удалять предыдущий текст, чтобы написать новое сообщение.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-11-22 20:32 UTC, aromanovnik commented on src/index.ts
> +const enum Route {
**Отлично!**: Здорово, что используется `enum`. Это не только улучшает читаемость кода, но и помогает избежать ошибок, связанных с использованием магических значений, делая код более поддерживаемым и понятным.

2024-11-22 20:32 UTC, aromanovnik commented on src/pages/profileSettings/profileSettings.hbs
> +      <form method="POST" class="settings__form">
**Надо исправить**: Обновление информации пользователя и смена пароля должны быть реализованы в виде отдельных форм, так как эти действия логически не связаны. Например, если пользователь хочет изменить только имя в чате, не следует требовать изменения пароля. Разделение форм улучшит удобство использования и предотвратит ненужные действия.

2024-11-22 20:32 UTC, aromanovnik commented on src/pages/profileSettings/ProfileSettings.ts
> +            const values = Object.fromEntries(formData as any);
**Можно лучше**: Использование типа `Any` считается плохой практикой, так как оно ослабляет типизацию и не предоставляет информации о данных, с которыми вы работаете. В случае с `FormData`, тип элементов заранее известен — это либо `File`, либо `string`. Эти элементы можно безопасно получить с помощью метода `forEach`, который есть у объекта `FormData`. Такой подход улучшит читаемость кода, обеспечит строгую типизацию и минимизирует ошибки, связанные с неожиданными типами данных.

2024-11-22 20:32 UTC, aromanovnik commented on src/pages/profileSettings/ProfileSettings.ts
> +              UserController.editPassword(values as EditPassword);
**Надо исправить**: Запрос на изменение пароля должен содержать только два поля: `newPassword` и `oldPassword`. Передача других данных, таких как имя или электронная почта, не имеет смысла и создает лишнюю нагрузку на сервер. Аналогично, при запросе на изменение данных пользователя, например имени или email, пароли передавать не нужно. Такой подход улучшает безопасность, упрощает обработку запросов на сервере и делает код более понятным.

<img width="1219" alt="Снимок экрана 2024-11-22 в 22 42 25" src="https://github.com/user-attachments/assets/c27f7383-02c4-4340-bd0d-e16300dca161">

<img width="1010" alt="Снимок экрана 2024-11-22 в 22 22 11" src="https://github.com/user-attachments/assets/df8eeea5-a216-42d0-a98a-00deebb3165f">

2024-11-22 20:32 UTC, aromanovnik commented on src/components/ChatMessageButtons/ChatMessageButtons.ts
> +          if (validatorMessage(values.message) && this.props.selectedChat) {
**Можно лучше**: После отправки сообщения текстовое поле ввода (input) должно очищаться. Это улучшит пользовательский опыт, так как пользователю не придется вручную удалять предыдущий текст, чтобы написать новое сообщение.

2024-11-22 20:32 UTC, aromanovnik commented on src/components/ChatMessageButtons/ChatMessageButtons.ts
> +          const formData = new FormData(event.target as HTMLFormElement);
**Можно лучше**: В проекте повторяется один и тот же код в нескольких местах. Лучше вынести его в отдельную функцию, чтобы соблюсти принцип DRY (Don’t Repeat Yourself). Это не только улучшит читаемость и поддержку кода, но и сделает его более модульным.

2024-11-24 15:04 UTC, IFabrichnov commented
Исправил обязательные замечания по разбитию настроек профиля и изменения пароля на разные формы, и из необязателбных сделал очистку инпута после отправки сообщения. Остальное посмотрю после принятия работы, тк уже отстаю от графика

2024-11-24 18:59 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. 

Что можно улучшить:
* Постарайтесь избавиться от использования типов `any` в коде (**В проекте их 40+**). Это делает код менее безопасным, так как `any` отключает проверку типов, что может привести к скрытым ошибкам. Если тип заранее не известен, что бывает редко, используйте `unknown`, так как он заставляет явно проверять тип перед использованием. Однако предпочтительнее сразу указывать конкретные типы, чтобы улучшить читаемость и надежность кода.
* Ошибки запросов лучше не просто выводить в `console`, а обрабатывать их и записывать в `Store`. Это позволяет подписываться на изменения в шаблонах и информировать пользователя об ошибке, например, отображая уведомление или сообщение. 

Желаю успехов в дальнейшей учебе!

2024-11-24 18:59 UTC, aromanovnik commented on src/controllers/AuthController.ts
> +    } catch (e: any) {
**Можно лучше**: Постарайтесь избавиться от использования типов `any` в коде (**В проекте их 40+**). Это делает код менее безопасным, так как `any` отключает проверку типов, что может привести к скрытым ошибкам. Если тип заранее не известен, что бывает редко, используйте `unknown`, так как он заставляет явно проверять тип перед использованием. Однако предпочтительнее сразу указывать конкретные типы, чтобы улучшить читаемость и надежность кода.

2024-11-24 18:59 UTC, aromanovnik commented on src/pages/profileSettings/ProfileSettings.ts
> +              UserController.editProfile(values as EditProfile);
**Можно лучше**: Ошибки запросов лучше не просто выводить в `console`, а обрабатывать их и записывать в `Store`. Это позволяет подписываться на изменения в шаблонах и информировать пользователя об ошибке, например, отображая уведомление или сообщение. Такой подход повышает удобство использования приложения и делает его более устойчивым, так как пользователи не остаются в неведении о возникших проблемах.

2024-11-25 15:27 UTC, merged